[server]
headless = true
enableCORS = false
runOnSave = true
enableXsrfProtection = true
maxUploadSize = 1024  # MB

[browser]
gatherUsageStats = false

[theme]
base = "light"  # "dark" si lo prefieres
primaryColor = "#2563EB"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#0F172A"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = true
