
[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = 8501

[theme]
base="dark"
primaryColor="#E27D60"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"
